
python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_4/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_4" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_4/tetra_4_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_4" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_4/561/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_4/561" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_4/647/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_4/647" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_5/tetra_5_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_5" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_5/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_5/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_5/561/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_5/561" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_5/647/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_5/647" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_6!/tetra_6_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_6!" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_6!/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_6!/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_6!/561/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_6!/561" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_6!/647/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_6!/647" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_1/tetra_1_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_1" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_1/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_1/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_1/561/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_1/561" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_1/647/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_1/647" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_2/tetra_2_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_2" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_2/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_2/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_2/561/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_2/561" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_2/647/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_2/647" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_3/tetra_3_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_3" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_3/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_3/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_3/561/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_3/561" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_3/647/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_3/647" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/ASM_2/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/ASM_2" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/ASM_2/ASM_2_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/ASM_2" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_12/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_12" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_12/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_12" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_12/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_12" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_12/tetra_12_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_12" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_13/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_13" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_13/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_13" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_13/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_13" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_13/tetra_13_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_13" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_14/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_14" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_14/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_14" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_14/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_14" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_14/tetra_14_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_14" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_7/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_7" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_7/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_7" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_7/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_7" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_7/tetra_7_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_7" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_8/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_8" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_8/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_8" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_8/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_8" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_8/tetra_8_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_8" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_9/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_9" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_9/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_9" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_9/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_9" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_9/tetra_9_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_9" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_10/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_10" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_10/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_10" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_10/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_10" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_10/tetra_10_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_10" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_11/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_11" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_11/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_11" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_11/647.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_11" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/tetra_11/tetra_11_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/tetra_11" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_29/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_29" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_29/Luca1_29_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_29" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_29/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_29/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_26/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_26" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_26/Luca1_26_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_26" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_26/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_26/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_23/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_23" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_23/Luca1_23_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_23" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_23/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_23/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_5/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_5" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_5/Luca1_5_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_5" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_6/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_6" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_6/Luca1_6_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_6" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_1/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_1" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_1/Luca1_1_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_1" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_2/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_2" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_2/Luca1_2_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_2" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_3/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_3" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_3/Luca1_3_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_3" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_4/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_4" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_4/Luca1_4_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_4" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_20/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_20" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_20/Luca1_20_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_20" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_20/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_20/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_17/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_17" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_17/Luca1_17_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_17" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_17/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_17/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_14/561.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_14" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_14/Luca1_14_MMStack_Default.ome.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_14" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu

python run.py --root "/Volumes/GoogleDrive/My Drive/01datasets/SIMRec/Lisa/September 2020/Luca1_14/488/488.tif" --out "/Volumes/GoogleDrive/My Drive/0main/0phd/plots-for-Lisa-2021/All_reconstructions_from_best_model/Lisa (Sep 2020)/Luca1_14/488" --scale 1 --task simin_gtout --model rcan --nch_in 9 --nch_out 1 --dataset fouriersim --weights "/Volumes/GoogleDrive/My Drive/01models/SIMRec/march/0312_SIMRec_rndAll_0309/final.pth" --ntrain 1 --ntest 200 --test  --n_resblocks 10 --n_resgroups 3 --n_feat 96 --norm hist --cpu
